[WIP] [Japneet | Priya] Add. verify service
hariharanweb/sample-gateway-registry pull request #14
Opened 2023-02-10 10:52 UTC by japneetbhatia

2023-02-14 07:35 UTC, hariharanweb requested changes

2023-02-14 07:35 UTC, hariharanweb commented on src/services/VerifyService.js
> +    const responseFromUrl = await Api.doGet(`${req.network_participant[0].subscriber_url}/ondc-site-verification.html`);
take subscriber_url as parameter

2023-02-14 07:35 UTC, hariharanweb commented on src/services/VerifyService.js
> +    const responseFromUrl = await Api.doGet(`${req.network_participant[0].subscriber_url}/ondc-site-verification.html`);
also request_id, signing_pub_key

2023-02-15 07:09 UTC, japneetbhatia commented on src/services/VerifyService.js
> +    const responseFromUrl = await Api.doGet(`${req.network_participant[0].subscriber_url}/ondc-site-verification.html`);
Updated

2023-02-15 12:22 UTC, shashank-on-codehunt approved these changes

2023-02-16 07:44 UTC, merged